/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package constructionwmanagement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author 1450
 */
public class MainFrame extends javax.swing.JFrame {
    
    

    /**
     * Creates new form MainFrame1
     */
    public MainFrame() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Raw Material Input");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(244, 13, 132, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Bags of Cement (50 Kg each):");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 210, 174, 15);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(230, 150, 376, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText(" Area of Plot (Sq. Ft.):");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 160, 124, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Sand (Cu. ft.):");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 260, 80, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Stone Aggregates 10 mm (Cu. ft.):");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 310, 195, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Stone Aggregates 20 mm (Cu. ft.):");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 380, 195, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Nos. of Bricks:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 430, 77, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Reinforcement Steel (kg):");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 480, 143, 15);

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(230, 210, 376, 25);

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(230, 260, 376, 25);

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(230, 310, 376, 25);

        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(230, 370, 376, 25);

        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(230, 420, 376, 25);

        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(230, 470, 376, 25);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image1.gif"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 10, 200, 130);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image2.gif"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(440, 10, 200, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 130, 650, 520);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("RCC Material Input");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(244, 13, 132, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Breadth (feet):");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 260, 174, 15);

        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jPanel2.add(jTextField8);
        jTextField8.setBounds(210, 210, 376, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Length (feet):");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 210, 80, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Thickness (feet):");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 310, 94, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Cement(Bags):");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 360, 82, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("20 mm Aggregates (Cft):");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 410, 139, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Msand (Cft):");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 470, 68, 15);

        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField9FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });
        jPanel2.add(jTextField9);
        jTextField9.setBounds(210, 260, 376, 25);

        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField10FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });
        jPanel2.add(jTextField10);
        jTextField10.setBounds(210, 310, 376, 25);

        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField11FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });
        jPanel2.add(jTextField11);
        jTextField11.setBounds(210, 360, 376, 25);

        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField12FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField12FocusLost(evt);
            }
        });
        jPanel2.add(jTextField12);
        jTextField12.setBounds(210, 410, 376, 25);

        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField13FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField13FocusLost(evt);
            }
        });
        jPanel2.add(jTextField13);
        jTextField13.setBounds(210, 460, 376, 25);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image3.gif"))); // NOI18N
        jPanel2.add(jLabel17);
        jLabel17.setBounds(210, 40, 200, 140);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(690, 130, 650, 520);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CONSTRUCTION WASTE MANAGMENT");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(250, 30, 930, 58);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1250, 660, 90, 30);

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1050, 660, 90, 30);

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1150, 660, 90, 30);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/construction.jpg"))); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 1450, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String area=jTextField1.getText();
        String cement1=jTextField2.getText();
        String sand=jTextField3.getText();
        String stone1=jTextField4.getText();
        String stone2=jTextField5.getText();
        String bricks=jTextField6.getText();
        String steel=jTextField7.getText();
        
        String length=jTextField8.getText();
        String breadth=jTextField9.getText();
        String thickness=jTextField10.getText();
        String cement2=jTextField11.getText();
        String aggregates=jTextField12.getText();
        String msand=jTextField13.getText();
        
        
        DataKeeper.area=area;
        DataKeeper.cement1=cement1;
        DataKeeper.sand=sand;
        DataKeeper.stone1=stone1;
        DataKeeper.stone2=stone2;
        DataKeeper.bricks=bricks;
        DataKeeper.steel=steel;
        DataKeeper.length=length;
        DataKeeper.breadth=breadth;
        DataKeeper.thickness=thickness;
        DataKeeper.cement2=cement2;
        DataKeeper.agggregat=aggregates;
        DataKeeper.msand=msand;
        
        if(area.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter Area of Plot");
        }
        else if(!area.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "Area of Plot should be in Integer only");
        }
        
        else if(cement1.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter Bags of Cement");
        }
        else if(!cement1.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "Bags of Cement should be in Integer only");
        }
        else if(sand.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter Sand");
        }
        else if(!sand.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "Sand should be in Integer only");
        }
        else if(stone1.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter 10mm Stone Aggregates");
        }
        else if(!stone1.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "10mm Stone Aggregates should be in Integer only");
        }
        else if(stone2.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter 20mm Stone Aggregates");
        }
        else if(!stone2.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "20mm Stone Aggregates should be in Integer only");
        }
        else if(bricks.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter No of Bricks");
        }
        else if(!bricks.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "Bricks should be in Integer only");
        }
        else if(steel.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter Reinforcement Steel");
        }
        else if(!steel.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "Reinforcement Steel should be in Integer only");
        }
        else if(length.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter Length");
        }
        else if(!length.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "Length should be in Integer only");
        }
        else if(breadth.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter Breadth");
        }
        else if(!breadth.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "Breadth should be in Integer only");
        }
        else if(thickness.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter Thickness");
        }
        else if(!thickness.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "Thickness should be in Integer only");
        }
        else if(cement2.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter Cement Bags");
        }
        else if(isDouble(cement2)==false)
        {
            JOptionPane.showMessageDialog(null, "Cement Bags should be in Number only");
            
        }
        else if(aggregates.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter Aggregates");
        }
         else if(isDouble(aggregates)==false)
        {
            JOptionPane.showMessageDialog(null, "20mm Aggregates should be in Number only");
            
        }
        else if(msand.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter Msand");
        }
         else if(isDouble(msand)==false)
        {
            JOptionPane.showMessageDialog(null, "Msand should be in Number only");
            
        }
        else
        {
            
      
//            System.out.println("User Entered Data For Raw construction ");
//            System.out.println(" Area of Plot-	bags of Cement-	Sand -Stone Aggregates 10mm -Stone Aggregates 20mm - Nos of Bricks -RCC");
//            System.out.println(area+" - "+cement1+" - "+sand+" - "+stone1+" - "+stone2+" - "+bricks+" - "+steel);
//            
//            
//            System.out.println("User Entered Data For RCC construction ");
//            System.out.println(" Length- Breadth- Thickness - RCC cement - aggregates - msand");
//            System.out.println(length+" - "+breadth+" - "+thickness+" - "+cement2+" - "+aggregates+" - "+msand);
//            
            new ProcessInit().initProcess();
            this.dispose();
            Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
            DataDisplayFrame e = new DataDisplayFrame();
            e.setVisible(true);
            e.setSize(dimension);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

      boolean isDouble(String num)
     {
         
        try
    {
        Double.parseDouble(num);
        return true;
    } 
        catch (NumberFormatException ex)
    {
        return false;
    }
         
     }
    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
          Color clr = new Color(51,161,222);
        jTextField1.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField1.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
        
        Color clr = new Color(51,161,222);
        jTextField2.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        
        Color clr = new Color(0,102,204);
        jTextField2.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        // TODO add your handling code here:
        
        Color clr = new Color(51,161,222);
        jTextField3.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        
        Color clr = new Color(0,102,204);
        jTextField3.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        // TODO add your handling code here:
        Color clr = new Color(51,161,222);
        jTextField4.setBorder(new LineBorder(clr,2));

    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField4.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
        Color clr = new Color(51,161,222);
        jTextField5.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField5.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
        // TODO add your handling code here:
        Color clr = new Color(51,161,222);
        jTextField6.setBorder(new LineBorder(clr,2));

    }//GEN-LAST:event_jTextField6FocusGained

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField6.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusGained
        // TODO add your handling code here:
        
        Color clr = new Color(51,161,222);
        jTextField7.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField7FocusGained

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField7.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained
        // TODO add your handling code here:
        Color clr = new Color(51,161,222);
        jTextField8.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField8.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusGained
        // TODO add your handling code here:
        Color clr = new Color(51,161,222);
        jTextField9.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField9FocusGained

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField9.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField9FocusLost

    private void jTextField10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusGained
        // TODO add your handling code here:
        Color clr = new Color(51,161,222);
        jTextField10.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField10FocusGained

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField10.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField10FocusLost

    private void jTextField11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusGained
        // TODO add your handling code here:
        Color clr = new Color(51,161,222);
        jTextField11.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField11FocusGained

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField11.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField12FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusGained
        // TODO add your handling code here:
        Color clr = new Color(51,161,222);
        jTextField12.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField12FocusGained

    private void jTextField12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField12.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField12FocusLost

    private void jTextField13FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusGained
        // TODO add your handling code here:
        Color clr = new Color(51,161,222);
        jTextField13.setBorder(new LineBorder(clr,2));
    }//GEN-LAST:event_jTextField13FocusGained

    private void jTextField13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusLost
        // TODO add your handling code here:
        Color clr = new Color(0,102,204);
        jTextField13.setBorder(new LineBorder(clr,1));
    }//GEN-LAST:event_jTextField13FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
